Fixed: Fix cross-app menu location issues (OFBIZ-13035)
Fixes mainMenuLocation missing in AR and AP web.xml files hence error
java.lang.RuntimeException: Error rendering included menu named [MainActionMenu]
at location []: java.lang.IllegalArgumentException: Could not find menu file
in location []