"Applied fix from trunk for revision: 1864721" ------------------------------------------------------------------------ r1864721 | jleroux | 2019-08-08 17:52:04 +0200 (jeu. 08 août 2019) | 9 lignes
Fixed: In Product Image Management Uploading file fails due to missing 
StatusValidChange
(OFBIZ-11148)
The error is
java.lang.Exception: Error in Service [updateContent]: Error: 
status change from [CTNT_IN_PROGRESS] to [IM_PENDING] is not allowed.

The issue does not exist in R16. So I guess it's because of OFBIZ-9907.

------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/ofbiz-framework/branches/release18.12@1864722 13f79535-47bb-0310-9956-ffa450edef68