Fixed: Geo Location functionality of facility contact information screen is not working (OFBIZ-7343)
Long ago I spotted an issue:

<<In French I got this js error message in console (else nothing apears anywhere)

SyntaxError: missing ) after argument list
...=9000&partyId=Company', 'Adresse d'expédition - Géolocalisation', '450', '550')

It's due to the quote in "Adresse d'expédition"
We could though commit by escaping the popUptitle, but I also think we should
change from the popup (and everywhere the same is used) to a modal layered
window.>>

Turned out that:
<<I had a quick look to see if we could not use a modal layer instead of a popup,
but it's not obvious to use modal layer from Freemarker. This does not mean that
it can't be done... I'll see later...>>

Here is a late workaround :)