Fixed: Error in ProductServicesScript.groovy]:(Cannot execute null+1) (OFBIZ-13079)
Fixes an error in countProductView service.

There is still an error reproducible in 18.12 (summarised)

Error running Groovy method ProductServicesScript::countProductView :
org.apache.ofbiz.entity.GenericEntityException: Error while inserting:
[GenericEntity:ProductCalculatedInfo](INSERT on table 'PRODUCT_CALCULATED_INFO'
caused a violation of foreign key constraint 'PRODCI_PROD' for key (GS-1000).
The statement has been rolled back.

So another Jira is needed.