No functional change, fixes a Javadoc issue
I can't check here (Win7) because of:

C:\projectsASF\ofbiz\framework\common\src\main\java\org\apache\ofbiz\common\
UrlServletHelper.java:251: error: unmappable character for encoding Cp1252
        str = str.replace("´╝?", "-");

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1777310 13f79535-47bb-0310-9956-ffa450edef68