A patch from Martin Becker "Missing BIRT libs in eclipse .classpath file" https://issues.apache.org/jira/browse/OFBIZ-6317
Because of missing JARs from the specialpurpose component birt in the eclipse .classpath file OFBiz could not be startet within eclipse without errors (NoClassDefFoundError while starting birt component).
With "starting within eclipse" I mean the configuration with hot code replacement like this: https://cwiki.apache.org/confluence/display/OFBIZ/Running+and+Debugging+OFBiz+in+Eclipse#RunningandDebuggingOFBizinEclipse-debuggingInEclipseHotClasses
I provide a patch for the .classpath file with 4 added libs from the specialpurpose/birt/lib folder.



git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1681848 13f79535-47bb-0310-9956-ffa450edef68