sendQuoteReportMail service was giving console error for missing subject & messagewrapper. Fixed the same issue.
Here is the console log for reference:

2010-03-24 10:01:18,146 (http-0.0.0.0-8443-4) [  ServiceDispatcher.java:601:INFO ] Sync service [order/sendMailMultiPart] finished in [8814] milliseconds
2010-03-24 10:01:18,146 (http-0.0.0.0-8443-4) [  ServiceDispatcher.java:601:INFO ] Sync service [order/sendMailFromScreen] finished in [9236] milliseconds
2010-03-24 10:01:18,146 (http-0.0.0.0-8443-4) [       ModelService.java:564:ERROR] [ModelService.validate] : {sendQuoteReportMail} : (OUT) Required test error: org.ofbiz.service.ServiceValidationException: Unknown parameter found: [sendQuoteReportMail.messageWrapper]Unknown parameter found: [sendQuoteReportMail.subject]
2010-03-24 10:01:18,147 (http-0.0.0.0-8443-4) [  ServiceDispatcher.java:495:ERROR] 
---- exception report ----------------------------------------------------------
Outgoing result (in runSync : sendQuoteReportMail) does not match expected requirements
Exception: org.ofbiz.service.ServiceValidationException
Message: Unknown parameter found: [sendQuoteReportMail.messageWrapper]Unknown parameter found: [sendQuoteReportMail.subject]
---- stack trace ---------------------------------------------------------------
org.ofbiz.service.ServiceValidationException: Unknown parameter found: [sendQuoteReportMail.messageWrapper]Unknown parameter found: [sendQuoteReportMail.subject]
org.ofbiz.service.ModelService.validate(ModelService.java:648)
org.ofbiz.service.ModelService.validate(ModelService.java:562)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:493)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:226)
org.ofbiz.service.GenericDispatcher.runSync(GenericDispatcher.java:160)
org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:336)
org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:637)
org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:383)
org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:224)
org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:87)
javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:266)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:568)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
java.lang.Thread.run(Thread.java:619)
--------------------------------------------------------------------------------

2010-03-24 10:01:18,148 (http-0.0.0.0-8443-4) [  ServiceDispatcher.java:516:INFO ] [[Sync service failed...- total:0.0,since last(Begin):0.0]] - 'order / sendQuoteReportMail'
2010-03-24 10:01:18,148 (http-0.0.0.0-8443-4) [  ServiceDispatcher.java:519:ERROR] 
---- exception report ----------------------------------------------------------
Service [sendQuoteReportMail] threw an unexpected exception/error
Exception: org.ofbiz.service.ServiceValidationException
Message: Unknown parameter found: [sendQuoteReportMail.messageWrapper]Unknown parameter found: [sendQuoteReportMail.subject]
---- stack trace ---------------------------------------------------------------
org.ofbiz.service.ServiceValidationException: Unknown parameter found: [sendQuoteReportMail.messageWrapper]Unknown parameter found: [sendQuoteReportMail.subject]
org.ofbiz.service.ModelService.validate(ModelService.java:648)
org.ofbiz.service.ModelService.validate(ModelService.java:562)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:493)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:226)
org.ofbiz.service.GenericDispatcher.runSync(GenericDispatcher.java:160)
org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:336)
org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:637)
org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:383)
org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:224)
org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:87)
javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:266)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:568)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
java.lang.Thread.run(Thread.java:619)
--------------------------------------------------------------------------------

2010-03-24 10:01:18,148 (http-0.0.0.0-8443-4) [    TransactionUtil.java:329:ERROR] 
---- exception report ----------------------------------------------------------
[TransactionUtil.rollback]
Exception: java.lang.Exception
Message: Stack Trace
---- stack trace ---------------------------------------------------------------
java.lang.Exception: Stack Trace
org.ofbiz.entity.transaction.TransactionUtil.rollback(TransactionUtil.java:328)
org.ofbiz.entity.transaction.TransactionUtil.rollback(TransactionUtil.java:310)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:526)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:226)
org.ofbiz.service.GenericDispatcher.runSync(GenericDispatcher.java:160)
org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:336)
org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:637)
org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:383)
org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:224)
org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:87)
javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:266)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:568)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
java.lang.Thread.run(Thread.java:619)
--------------------------------------------------------------------------------

2010-03-24 10:01:18,153 (http-0.0.0.0-8443-4) [    TransactionUtil.java:339:INFO ] [TransactionUtil.rollback] transaction rolled back
2010-03-24 10:01:18,153 (http-0.0.0.0-8443-4) [    TransactionUtil.java:269:WARN ] [TransactionUtil.commit] Not committing transaction, status is No Transaction (6)
2010-03-24 10:01:18,153 (http-0.0.0.0-8443-4) [     RequestHandler.java:638:INFO ] Ran Event [service:#sendQuoteReportMail] from [request], result is [error]
2010-03-24 10:01:18,169 (http-0.0.0.0-8443-4) [       SequenceUtil.java:336:INFO ] Got bank of sequenced IDs for [ServerHitBin]; curSeqId=10320, maxSeqId=10330, bankSize=10
2010-03-24 10:01:18,259 (http-0.0.0.0-8443-4) [     RequestHandler.java:424:ERROR] Request sendQuoteReportMail caused an error with the following message: {Unknown parameter found: [sendQuoteReportMail.messageWrapper], Unknown parameter found: [sendQuoteReportMail.subject]}
2010-03-24 10:01:18,259 (http-0.0.0.0-8443-4) [     RequestHandler.java:742:INFO ] Rendering View [EditQuoteReportMail], 

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@926936 13f79535-47bb-0310-9956-ffa450edef68