Fixed: Several IllegalArgumentExceptions
Don't use all service parameters in where condition since entities don't have all fields which results in:

java.lang.IllegalArgumentException: FieldName product not found for entity: ProductStore
	at org.apache.ofbiz.entity.condition.EntityExpr.checkRhsType(EntityExpr.java:199)
	at org.apache.ofbiz.entity.condition.EntityExpr.makeWhereString(EntityExpr.java:118)
	at org.apache.ofbiz.entity.condition.EntityJoinOperator.addSqlValue(EntityJoinOperator.java:74)
	at org.apache.ofbiz.entity.condition.EntityConditionListBase.makeWhereString(EntityConditionListBase.java:77)
	at org.apache.ofbiz.entity.condition.EntityJoinOperator.addSqlValue(EntityJoinOperator.java:74)
	at org.apache.ofbiz.entity.condition.EntityConditionListBase.makeWhereString(EntityConditionListBase.java:77)
	at org.apache.ofbiz.entity.datasource.GenericDAO.makeConditionWhereString(GenericDAO.java:828)
	at org.apache.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:732)
	at org.apache.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:140)
	at org.apache.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1579)
	at org.apache.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1613)
	at org.apache.ofbiz.entity.util.EntityQuery.query(EntityQuery.java:455)
	at org.apache.ofbiz.entity.util.EntityQuery.queryList(EntityQuery.java:380)
	at org.apache.ofbiz.entity.util.EntityQuery.queryOne(EntityQuery.java:421)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ProductStoreServices.isStoreInventoryAvailableOrNotRequired(ProductStoreServices.groovy:357)