No functional change, dummy change to test documentation generation on site.
Removes a redundant "build"?

This is weird "/build/build/" returned by Builbot
at https://ci.apache.org/builders/ofbizTrunkFrameworkPlugins/builds/525/
	steps/upload_1/logs/err.text
	
twisted.spread.pb.RemoteError: [Errno 2] 
No such file or directory: '/home/buildslave/slave/ofbizTrunkFrameworkPlugins/
	build/build/asciidoc/ofbizdoc'

When it works for "build/docs/javadoc"

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/ofbiz-framework/trunk@1846980 13f79535-47bb-0310-9956-ffa450edef68