Fixed: Replace Asm select plugin with Select2. (OFBIZ-10113)
I found this error in trunk demo error.log

2018-01-16 15:45:48,684 |jsse-nio-8443-exec-3 |FreeMarkerWorker              |E| null
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> userLogin  [in template 
"component://common-theme/template/includes/SetMultipleSelectJs.ftl" at line 32, column 20]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${userLogin.lastLocale!"en"}  [in template 
"component://common-theme/template/includes/SetMultipleSelectJs.ftl" at line 32, column 18]
----

This fixes it

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/ofbiz-framework/trunk@1821268 13f79535-47bb-0310-9956-ffa450edef68