No functional change.
While reviewing r1813634, I found that we could use a multi-catch, and while
doing so found that we were missing a CertificateException according to Eclipse

Confirmed by Java:
:compileJava
ofbiz\framework\service\src\main\java\org\apache\ofbiz\service\rmi\socket\ssl\
SSLServerSocketFactory.java:75: error: 
unreported exception CertificateException; must be caught or declared to be
thrown
                ks.load(fis, passphrase);

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/ofbiz-framework/trunk@1813671 13f79535-47bb-0310-9956-ffa450edef68