Fixed: Reducing scope of variables in org.apache.ofbiz.base package (OFBIZ-10478)
Reverts
- public static Map<String, Object> testService(
+ private static Map<String, Object> testService(

This was the real (and AFAIK only) error:
|W| [JUNIT (error)] - testBasicJavaInvocation :
org.apache.ofbiz.service.GenericServiceException: Service [testScv]
specified Java method (invoke attribute) does not exist
(org.apache.ofbiz.common.CommonServices.testService(...
[..]
Caused by: java.lang.NoSuchMethodException:
org.apache.ofbiz.common.CommonServices.testService(...
	at java.lang.Class.getMethod(Class.java:2108) ~[?:?]
	at org.apache.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(...

I think this has no been tested with integration test