Fixed: Refactor ContentWorkerInterface methods signatures (OFBIZ-9164)
If you go at: catalog/control/main then open the lookup on the left for category
 id, click the first category (20111) and then click on search, you will be 
prompted with this:
java.lang.IllegalArgumentException: Error running script at location 
[component://product/groovyScripts/catalog/find/KeywordSearch.groovy]: 
java.lang.NullPointerException

This is the result of the changes I made for this issue 1.5 years ago.

I missed the case where a null is passed instead of a dispatcher in
getProductCategoryContentAsText()
which is then used inside of getProductCategoryContentAsText:
ContentWorker.renderContentAsText()
The problem is, that the method renderContentAsText as a result of my changes 
uses the dispatcher to get the delegator.
Because the dispatcher is a given a null value at this point, this results in a 
null pointer.

The solution was to introduce and abstract prettyPrintConstraint method with a 
LocalDispatcher as argument and to implement it in CategoryConstraint class. 

Other implementations don't use getProductCategoryContentAsText so can simply 
return null. They will not be used anywhere anyway.

CatalogConstraint.prettyPrintConstraint with a delegator is now not
used OOTB but I prefer to keep its implementation for custom projects which 
might use it in other circumstances. I though put a TODO to possibly simply
return null.

Also while at it remove a unused requestParams variable in ProductSearchSession

Thanks: Dennis Balkir for the detailed reporting

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/ofbiz-framework/trunk@1835891 13f79535-47bb-0310-9956-ffa450edef68