Fixed: Upgrade to gradle 7.6 - support jdk 11 -> 17 (OFBIZ-12400)
> java.lang.IllegalArgumentException: Unsupported class file major version 61

This might require a version upgrade for Jersey to a version that supports Java 17 .
Jersey seems to repackage ASM for bytecode transformations.

The bundled version does not support Java 17 .
An upgrade to jersey 2.37 should do the trick
https://github.com/eclipse-ee4j/jersey/releases/tag/2.37 .

Thanks: Ioan Eugen Stan