Bug fix.
Added missing argument parameters in Macro renderContentBegin.

It was giving error on console when we render content in pdf file.

Error was coming : --

2010-12-27 19:51:42,033 (http-0.0.0.0-8443-4) [ Log4JLoggerFactory.java:96 :ERROR]

Macro renderContentBegin has no such argument: editContainerStyle
The problematic instruction:
----------
==> macro renderContentBegin [on line 52, column 1 in component://widget/templates/foScreenMacroLibrary.ftl]
 in user-directive renderContentBegin [on line 1, column 1 in Mon Dec 27 19:51:42 IST 2010]
----------

Java backtrace for programmers:
----------
freemarker.template.TemplateException: Macro renderContentBegin has no such argument: editContainerStyle
    at freemarker.core.Environment.visit(Environment.java:564)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
    at freemarker.core.Environment.visit(Environment.java:209)
    at freemarker.core.Environment.include(Environment.java:1482)
    at org.ofbiz.widget.screen.MacroScreenRenderer.executeMacro(MacroScreenRenderer.java:95)
    at org.ofbiz.widget.screen.MacroScreenRenderer.renderContentBegin(MacroScreenRenderer.java:364)
    at org.ofbiz.widget.screen.ModelScreenWidget$Content.renderWidgetString(ModelScreenWidget.java:1181)
    at org.ofbiz.widget.screen.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:136)
    at org.ofbiz.widget.screen.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:227)
    at org.ofbiz.widget.screen.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:136)
    at org.ofbiz.widget.screen.ModelScreenWidget$DecoratorSection.renderWidgetString(ModelScreenWidget.java:703)
    at org.ofbiz.widget.screen.ModelScreenWidget$SectionsRenderer.render(ModelScreenWidget.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:840)
    at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:106)
    at freemarker.core.MethodCall._getAsTemplateModel(MethodCall.java:93)
    at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
    at freemarker.core.Expression.getStringValue(Expression.java:93)
    at freemarker.core.StringBuiltins$StringBuiltIn._getAsTemplateModel(StringBuiltins.java:71)
    at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
    at freemarker.core.Expression.getStringValue(Expression.java:93)
    at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
    at freemarker.core.Environment.visit(Environment.java:209)
    at freemarker.core.MixedContent.accept(MixedContent.java:92)
    at freemarker.core.Environment.visit(Environment.java:209)
    at freemarker.core.EscapeBlock.accept(EscapeBlock.java:84)
    at freemarker.core.Environment.visit(Environment.java:209)
    at freemarker.core.MixedContent.accept(MixedContent.java:92)
    at freemarker.core.Environment.visit(Environment.java:209)
    at freemarker.core.Environment.process(Environment.java:189)
    at org.ofbiz.base.util.template.FreeMarkerWorker.renderTemplate(FreeMarkerWorker.java:216)
    at org.ofbiz.widget.screen.HtmlWidget.renderHtmlTemplate(HtmlWidget.java:205)
    at org.ofbiz.widget.screen.HtmlWidget$HtmlTemplate.renderWidgetString(HtmlWidget.java:250)
    at org.ofbiz.widget.screen.HtmlWidget.renderWidgetString(HtmlWidget.java:110)
    at org.ofbiz.widget.screen.ModelScreenWidget$PlatformSpecific.renderWidgetString(ModelScreenWidget.java:1000)
    at org.ofbiz.widget.screen.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:136)
    at org.ofbiz.widget.screen.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:227)
    at org.ofbiz.widget.screen.ModelScreen.renderScreenString(ModelScreen.java:394)
    at org.ofbiz.widget.screen.ModelScreenWidget$DecoratorScreen.renderWidgetString(ModelScreenWidget.java:671)
    at org.ofbiz.widget.screen.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:136)
    at org.ofbiz.widget.screen.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:227)
    at org.ofbiz.widget.screen.ModelScreen.renderScreenString(ModelScreen.java:394)
    at org.ofbiz.widget.screen.ScreenRenderer.render(ScreenRenderer.java:135)
    at org.ofbiz.widget.screen.ScreenRenderer.render(ScreenRenderer.java:97)
    at org.ofbiz.widget.screen.ScreenFopViewHandler.render(ScreenFopViewHandler.java:81)
    at org.ofbiz.webapp.control.RequestHandler.renderView(RequestHandler.java:842)
    at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:558)
    at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:227)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:269)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:852)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:619) 
    
    
Thanks to Amit Sharma for the contribution.     

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1053285 13f79535-47bb-0310-9956-ffa450edef68